### ISSUE TITLE
Create a function coerce!/2

### ISSUE THREAD

**Issue by lowks** [moxley/coercion#2]
It would be nice if Coercion had a `coerce!/2` so that I can replace this: 

`is_residential: String.to_existing_atom(row[:is_residential])` with
`is_residential: coerce!(row[:is_residential, :boolean)` instead of 

```
{:ok, is_residential} = coerce(row[:is_residential], :boolean)
is_residential: is_residential
```

**Comment by moxley** [comment]
@lowks: Your example is something that Ecto.Schema is really good at. I would suggest looking into that, and also check out the `params` package that wraps around Ecto.Schema.
